service: auth-demo 
image: gitnvincadonis/auth-demo 

registry:
  server: ghcr.io
  username: GITnvincAdonis
  password:
    - KAMAL_REGISTRY_PASSWORD


# Deploy to these servers.
servers:
  web:
    hosts:
      - <%= ENV.fetch("KAMAL_HOST") %>
      # Assumes traefik will handle proxy so no need to setup kamal default proxy.
    proxy: false
    options:
      network:
        - traefik_proxy # A custom docker network that the traefik container is running on
        # This assumes a running postgress container lives on the VPS. 
        # THe allow option allows the application and the database to connect.
        - postgres-pgadmin_postgres-network

labels:
  traefik.enable: "true"
  traefik.http.routers.service_name.rule: "Host(`service_name.org`)"
  traefik.http.routers.service_name.entrypoints: "websecure" # assumes VPS has certificates setup
  traefik.http.routers.service_name.tls: "true" # enables tls crypt session handshake between server and clients 
  traefik.http.routers.service_name.tls.certresolver: "letsencrypt" # The built in traefik certs resolver
  traefik.http.services.service_name.loadbalancer.server.port: "3000" # Service (Rails app port inside container)
  traefik.docker.network: "traefik_proxy" # Matches the option set in the server configuration above


# Inject ENV variables into containers (secrets come from .kamal/secrets).
env:
  secret:
    - RAILS_MASTER_KEY
    - DATABASE_URL
    - GOOGLE_CLIENT_ID
    - GOOGLE_CLIENT_SECRET

  clear: {}

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"

# Use a persistent storage volume for sqlite database files and local Active Storage files.
# Recommended to change this to a mounted volume path that is backed up off server.
volumes:
  - "service_name_storage:/rails/storage"

# Bridge fingerprinted assets, like JS and CSS, between versions to avoid
# hitting 404 on in-flight requests. Combines all files from new and old
# version inside the asset_path.
asset_path: /rails/public/assets

# Configure the image builder.
builder:
  arch: amd64

ssh:
  user: <%= ENV.fetch("KAMAL_SSH_USER") %>
  port: <%= ENV.fetch("KAMAL_SSH_PORT").to_i %>
  keys:
    - <%= ENV.fetch("KAMAL_SSH_KEY") %>
