name: CI

on:
  push:
  pull_request:

jobs:
  bundle_install:
    runs-on: ubuntu-latest
    container:
      image: nvincadonis/ruby-npm-postgres:latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: bundle-${{ runner.os }}-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            bundle-${{ runner.os }}-
      - name: Install gems
        run: |
          bundle config set --local path 'vendor/bundle'
          bundle install

  rspec:
    runs-on: ubuntu-latest
    needs: bundle_install
    container:
      image: nvincadonis/ruby-npm-postgres:latest
    services:
      db:
        image: postgres:15
        env:
          POSTGRES_DB: auth_demo_development
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    env:
      DATABASE_URL: postgres://postgres:postgres@db:5432/auth_demo_development
      RAILS_ENV: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: bundle-${{ runner.os }}-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            bundle-${{ runner.os }}-
      - name: Install gems
        run: |
          bundle config set --local path 'vendor/bundle'
          bundle check || bundle install
      - run: bundle exec rails db:prepare
      - run: bundle exec rspec

  rubocop:
    runs-on: ubuntu-latest
    needs: bundle_install
    container:
      image: nvincadonis/ruby-npm-postgres:latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: bundle-${{ runner.os }}-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            bundle-${{ runner.os }}-

      - name: Install gems
        run: |
          bundle config set --local path 'vendor/bundle'
          bundle check || bundle install
      - run: bundle exec rubocop

  deploy:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: [rspec, rubocop]
    runs-on: ubuntu-latest

    steps:
      - name: install gems
        run: |
          bundle config set --local path 'vendor/bundle'
          bundle check || bundle install
      - name: deploy
        run: kamal deploy -v
